apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
spec:
  params:
    - name: IMAGE
    - name: DOCKERFILE
      default: ./app/Dockerfile
    - name: CONTEXT
      default: .
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      script: |
        #!/busybox/sh
        /kaniko/executor \
          --dockerfile=$(params.DOCKERFILE) \
          --context=$(params.CONTEXT) \
          --destination=$(params.IMAGE)
