apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: build-and-deploy-template
